# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c1c575a55dd019d84b494141890904e8cff2618ed7f7d14339f6c7c66ac5a8fcf797da74edee893b26dd31b589a61dda3752e1e0dda77aaf9abfce2457533776

test:
  secret_key_base: c78933c731ac03ae65a21c5c183402cd03a41353325cf6688389623fa6cf8962479b170e1bca63128a4857399c626c31aab70a46a9da181ac369bd2b63f68eec

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
